import React, { useCallback, useEffect, useState } from "react";
import api, { BASE_API_URL } from "../../../utils/api";
import "./AdminAccounts.css";

const permissionLabels = { DASHBOARD: "Dashboard", ORDERS: "Orders", INVENTORY: "Inventory", QUOTATIONS: "Quotations", USERS: "Users & dealerships", STOCK_APPROVALS: "Stock approvals", PRODUCTS: "Products", BLOGS: "Blogs", ADMIN_ACCOUNTS: "Admin accounts" };
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem("authToken")}` });
const blank = { name: "", email: "", phoneNumber: "", permissions: [] };

export default function AdminAccounts() {
  const [admins, setAdmins] = useState([]); const [permissions, setPermissions] = useState([]); const [modal, setModal] = useState(null); const [form, setForm] = useState(blank); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await api.get(`${BASE_API_URL}/admin/admin-accounts`, { headers: auth() }); setAdmins(response.data.admins || []); setPermissions(response.data.availablePermissions || []); }, []);
  useEffect(() => { load(); }, [load]);
  const toggle = permission => setForm(current => ({ ...current, permissions: current.permissions.includes(permission) ? current.permissions.filter(value => value !== permission) : [...current.permissions, permission] }));
  const save = async event => { event.preventDefault(); setBusy(true); try { if (modal.mode === "add") await api.post(`${BASE_API_URL}/admin/admin-accounts`, form, { headers: auth() }); else await api.patch(`${BASE_API_URL}/admin/admin-accounts/${modal.admin._id}`, { name: form.name, email: form.email, permissions: form.permissions, isActive: form.isActive }, { headers: auth() }); setModal(null); setForm(blank); await load(); } finally { setBusy(false); } };
  const openEdit = admin => { setForm({ name: admin.name, email: admin.email, phoneNumber: admin.phoneNumber, permissions: admin.adminPermissions || [], isActive: admin.isActive }); setModal({ mode: "edit", admin }); };
  return <main className="admin-accounts container py-4"><header><div><span>ACCESS CONTROL</span><h2>Admin accounts</h2><p>Create individual OTP accounts and choose which modules each administrator can use.</p></div><button onClick={() => { setForm(blank); setModal({ mode: "add" }); }}><i className="fas fa-user-plus"/>Add administrator</button></header><section className="admin-account-list">{admins.map(admin => <article key={admin._id}><div className="admin-avatar">{admin.name?.slice(0, 1).toUpperCase()}</div><div className="admin-identity"><h4>{admin.name}</h4><p>{admin.phoneNumber} · {admin.email}</p><div>{(admin.adminPermissions || []).map(permission => <span key={permission}>{permissionLabels[permission] || permission}</span>)}{!admin.adminPermissions?.length && <em>No module access</em>}</div></div><span className={`account-state ${admin.isActive ? "active" : "disabled"}`}>{admin.isActive ? "Active" : "Disabled"}</span><button className="edit-account" onClick={() => openEdit(admin)}><i className="fas fa-pen"/>Manage</button></article>)}</section>{modal && <div className="admin-account-backdrop"><form className="admin-account-modal" onSubmit={save}><header><div><h3>{modal.mode === "add" ? "Add administrator" : "Manage administrator"}</h3><p>Login OTP will be sent to this account’s mobile number.</p></div><button type="button" className="close-account" onClick={() => setModal(null)}>×</button></header><div className="admin-account-body"><div className="account-form-grid"><label>Name<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/></label><label>Email<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })}/></label></div><label>Mobile number<input required disabled={modal.mode === "edit"} inputMode="numeric" pattern="[0-9]{10}" maxLength="10" value={form.phoneNumber} onChange={event => setForm({ ...form, phoneNumber: event.target.value.replace(/\D/g, "") })}/></label><fieldset><legend>Module access</legend><div className="permission-grid">{permissions.map(permission => <label key={permission}><input type="checkbox" checked={form.permissions.includes(permission)} onChange={() => toggle(permission)}/><span><i className="fas fa-check"/>{permissionLabels[permission] || permission}</span></label>)}</div></fieldset>{modal.mode === "edit" && <label className="active-switch"><input type="checkbox" checked={form.isActive} onChange={event => setForm({ ...form, isActive: event.target.checked })}/><span>Account active</span></label>}</div><footer><button type="button" className="cancel-account" onClick={() => setModal(null)}>Cancel</button><button disabled={busy}>{busy ? "Saving…" : "Save administrator"}</button></footer></form></div>}</main>;
}
